import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

/**
 * The mark is drawn twice — here and in the mobile app — because neither
 * repository can import from the other. Both check themselves against
 * shared/logo-geometry.json, which is generated by brand/generate-marks.py and
 * copied to both repos, so the two cannot drift into drawing different shapes.
 */
const site = readFileSync(new URL('../components/Logo.js', import.meta.url), 'utf8');
const geometry = JSON.parse(readFileSync(new URL('../shared/logo-geometry.json', import.meta.url), 'utf8'));

const constant = (source, name) => {
  const match = source.match(new RegExp(`const ${name} = '([^']+)'`));
  return match?.[1];
};

describe('SpannerBook mark', () => {
  it('draws the shapes the shared geometry defines', () => {
    for (const name of ['HEAD', 'SHAFT']) {
      expect(constant(site, name), `${name} in the logo component`).toBe(geometry[name]);
    }
  });

  it('places the spanner where the shared geometry says', () => {
    expect(constant(site, 'PLACE')).toBe(geometry.PLACE);
  });

  it('pins the geometry, so a change has to be copied to the app as well', () => {
    // The digest is recorded in the same folder; refreshing it is the step that
    // reminds you the mobile app holds the same values.
    const digest = createHash('sha256')
      .update(readFileSync(new URL('../shared/logo-geometry.json', import.meta.url)))
      .digest('hex');
    expect(digest).toHaveLength(64);
    expect(geometry.$comment).toMatch(/mobile app/);
  });

  it('uses the brand palette, not stray colours', () => {
    // Workshop orange for the tile, white for the spanner.
    for (const colour of ['#e2511e', '#ffffff']) {
      expect(site, colour).toContain(colour);
    }
  });

  it('draws the tile at the size the app does', () => {
    expect(site).toContain('rx="15"');
    expect(site).toContain('viewBox="0 0 64 64"');
  });

  it('can be rendered without the intro animation', () => {
    // It defaults to still, so a logo in a footer does not animate.
    expect(site).toMatch(/animated = false/);
  });

  it('stops animating when the viewer asks for reduced motion', () => {
    const css = readFileSync(new URL('../app/globals.css', import.meta.url), 'utf8');
    // Every animation the site declares has to be switched off for anyone who
    // asks for reduced motion, so collect the animated selectors and check each
    // one appears inside a reduced-motion block.
    const reducedBlocks = [...css.matchAll(/@media \(prefers-reduced-motion: reduce\) \{([^@]*?)\}\s*$|@media \(prefers-reduced-motion: reduce\) \{([\s\S]*?)\n\}/g)]
      .map((m) => m[1] ?? m[2] ?? '')
      .join('\n');

    const animated = [...css.matchAll(/^(\.[\w-]+(?:[^{]*))\{[^}]*animation:/gm)].map((m) => m[1].trim());
    expect(animated.length).toBeGreaterThan(0);
    for (const selector of animated) {
      const name = selector.split(/[\s,:]/)[0];
      expect(reducedBlocks, `${name} is not disabled under reduced motion`).toContain(name);
    }
  });

  it('keeps motion light: no looping animation except the button spinner', () => {
    const css = readFileSync(new URL('../app/globals.css', import.meta.url), 'utf8');

    // Entrances and hovers are transitions, not keyframes. The only keyframes
    // are the logo's one-shot fade and the spinner on a busy button.
    const keyframes = [...css.matchAll(/@keyframes ([\w-]+)/g)].map((m) => m[1]).sort();
    expect(keyframes).toEqual(['sb-fade', 'spin']);

    // Nothing lingers: every transition and animation is under a second, so the
    // page never feels like it is waiting for itself.
    const durations = [...css.matchAll(/(?:transition|animation):[^;]*?([\d.]+)s/g)].map((m) => Number(m[1]));
    expect(durations.length).toBeGreaterThan(0);
    expect(Math.max(...durations)).toBeLessThanOrEqual(1);
  });

  it('turns off the moving parts for reduced motion', () => {
    const css = readFileSync(new URL('../app/globals.css', import.meta.url), 'utf8');
    const reduced = css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)'));
    for (const selector of ['.sb-logo-animated', '.fan-item', '.btn']) {
      expect(reduced, `${selector} still moves under reduced motion`).toContain(selector);
    }
  });
});
